export const categoryMap: Record<string, { label: string; color: string }> = {
    musica: { label: "Música", color: "bg-blue-500 text-white" },
    teatro: { label: "Teatro", color: "bg-purple-500 text-white" },
    tecnologia: { label: "Tecnología", color: "bg-green-500 text-white" },
    deporte: { label: "Deporte", color: "bg-red-500 text-white" },
    infantil: { label: "Infantil", color: "bg-yellow-500 text-black" },
    moda: { label: "Moda", color: "bg-pink-500 text-white" },
    arte: { label: "Arte", color: "bg-indigo-500 text-white" },
    feria: { label: "Feria", color: "bg-orange-500 text-white" },
    concierto: { label: "Concierto", color: "bg-teal-500 text-white" },
    gastronomico: { label: "Gastronómico", color: "bg-amber-500 text-black" },
    politico: { label: "Político", color: "bg-gray-700 text-white" },
    remoto: { label: "Remoto", color: "bg-cyan-500 text-white" },
    educativo: { label: "Educativo", color: "bg-lime-500 text-black" },
    religioso: { label: "Religioso", color: "bg-rose-500 text-white" },
    recaudacion: { label: "Recaudación", color: "bg-teal-600 text-white" },
    ambiental: { label: "Ambiental", color: "bg-green-700 text-white" },
    cine: { label: "Cine y Televisión", color: "bg-blue-700 text-white" },
    networking: { label: "Networking", color: "bg-gray-600 text-white" },
    videojuegos: { label: "Videojuegos", color: "bg-indigo-700 text-white" },
  };